CREATE TABLE IF NOT EXISTS pdf_personalizado (
    id INT AUTO_INCREMENT PRIMARY KEY,
    module_id INT NOT NULL DEFAULT 0,
    user_id INT NULL,
    nome_solicitante VARCHAR(255) NOT NULL,
    descricao_alteracoes TEXT NOT NULL,
    status ENUM('realizado', 'pagamento_confirmado', 'em_confeccao', 'entregue') NOT NULL DEFAULT 'pagamento_confirmado',
    preco_pago DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    desconto_aplicado DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    anexo1_base64 LONGTEXT NULL,
    anexo1_nome VARCHAR(255) NULL,
    anexo2_base64 LONGTEXT NULL,
    anexo2_nome VARCHAR(255) NULL,
    anexo3_base64 LONGTEXT NULL,
    anexo3_nome VARCHAR(255) NULL,
    pdf_entrega_base64 LONGTEXT NULL,
    pdf_entrega_nome VARCHAR(255) NULL,
    realizado_at DATETIME NULL,
    pagamento_confirmado_at DATETIME NULL,
    em_confeccao_at DATETIME NULL,
    entregue_at DATETIME NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_user_id (user_id),
    INDEX idx_status (status),
    INDEX idx_module_id (module_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
